repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: zsh -c 'env/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]